### ISSUE TITLE
IllegalStateException for yungscavebiomes:falling_icicle

### ISSUE THREAD

**Issue by bradyj04** [yungnickyoung/YUNGs-Cave-Biomes#14]
Will paste the error here, it did result in a crash, unsure what exactly could be causing it. This is fabric, 1.20.1. Note: before the crash, I broke an ice block in a cave and the icicle fell. Then crashed, I'm guessing since that is mentioned in the error code there is an issue specifically with the icicles. 
 [Server thread/ERROR] (Minecraft) Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:damage_type / yungscavebiomes:falling_icicle]' from registry FakeRegistry[registryKey=ResourceKey[minecraft:root / minecraft:damage_type], defaultId=polymer:fake_damage, defaultValue=class_8110[msgId=, scaling=NEVER, exhaustion=0.0, effects=HURT, deathMessageType=DEFAULT]]
at net.minecraft.class_6880$class_6883.comp_349(class_6880.java:167) ~[server-intermediary.jar:?]
at net.minecraft.class_1282.method_48792(class_1282.java:140) ~[server-intermediary.jar:?]
at net.minecraft.class_1282.method_5514(class_1282.java:105) ~[server-intermediary.jar:?]
at net.minecraft.class_1657.method_5643(class_1657.java:912) ~[server-intermediary.jar:?]
at net.minecraft.class_3222.method_5643(class_3222.java:732) ~[server-intermediary.jar:?]
at net.minecraft.class_1540.method_32879(class_1540.java:255) ~[server-intermediary.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
at net.minecraft.class_1540.method_5747(class_1540.java:254) ~[server-intermediary.jar:?]
at net.minecraft.class_2248.method_9554(class_2248.java:457) ~[server-intermediary.jar:?]
at net.minecraft.class_1297.method_5623(class_1297.java:1287) ~[server-intermediary.jar:?]
at net.minecraft.class_1297.method_5784(class_1297.java:738) ~[server-intermediary.jar:?]
at net.minecraft.class_1540.method_5773(class_1540.java:138) ~[server-intermediary.jar:?]
at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[server-intermediary.jar:?]
at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[server-intermediary.jar:?]
at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[server-intermediary.jar:?]
at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
... 5 more

**Comment by bradyj04** [comment]
For anyone else who has this issue i recommend deleting everything besides the world etc in your .minecraft folder, unsure what happened config wise but something was colliding and causing the error.

**Comment by bradyj04** [comment]
nevermind it back, it also seems to happen with vines. It seems to be when entities walk under and it falls or when into the vines, also players. But it isn't every time, sadly.

**Comment by yungnickyoung** [comment]
Gonna redirect this to #18
