### ISSUE TITLE
[Crash] Collision with prickly vines and icicles can cause a crash

### ISSUE THREAD

**Issue by kawazoe** [yungnickyoung/YUNGs-Cave-Biomes#18]
I noticed random crashes while walking around some portions of a new world I just created. After looking at the logs, it turns out it's caused by bats randomly getting hurt by prickly vines.

I couldn't reproduce the issue manually. Trying to spawn a bat near the vine didn't cause any issue, and the bat did take damage. I think this might only happen in partially loaded chunks.

Here's the crash log:

[crash-2024-11-07_18.53.16-server.txt](https://github.com/user-attachments/files/17668168/crash-2024-11-07_18.53.16-server.txt)

EDIT: After playing for a bit, the server started crashing more and more frequently until I couldn't even log on anymore. It's the same crash every time.

**Comment by kawazoe** [comment]
I took some time to look at the logs and code and, after testing a few things, I managed to simplify the callstack a little.

Looking at the logs, I first thought the bug might actually be in CookingForBlockHead; maybe something related to how they handle LivingDamage events for the CowInAJar feature. They did change that code between 1.20.1 and now, so I tried disabling it. I get a similar error, but this time in a different part of the stack:

```
java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:damage_type / yungscavebiomes:prickly_vines]' from registry FakeRegistry[registryKey=ResourceKey[minecraft:root / minecraft:damage_type], defaultId=polymer:fake_damage, defaultValue=class_8110[msgId=, scaling=NEVER, exhaustion=0.0, effects=HURT, deathMessageType=DEFAULT]]
    at knot//net.minecraft.class_6880$class_6883.comp_349(class_6880.java:167)
    at knot//net.minecraft.class_1282.method_48792(class_1282.java:140)
    at knot//net.minecraft.class_8143.<init>(class_8143.java:25)
    at knot//net.minecraft.class_3218.method_48760(class_3218.java:1043)
    at knot//net.minecraft.class_1309.method_5643(class_1309.java:1196)
    at knot//com.yungnickyoung.minecraft.yungscavebiomes.block.PricklyVinesBlock.method_9548(PricklyVinesBlock.java:57)
```
_the rest is similar_

This all appear to be in minecraft code directly. My modding experience is very sparse, but I suspect there might be a missing registration for the damage type.

**Comment by yungnickyoung** [comment]
What happens if you remove Universal Graves? I'm wondering if its dependency, Polymer, somehow causes issues with the way I registered the DamageType.

**Comment by Pa-nts** [comment]
Has any progress been made on this error? I seem to be having a similar issue on a custom mod pack server I've been working on. My current solution to avoid crashes is to use Neruina. While this does help the issue it still seems to be present.

**Comment by yungnickyoung** [comment]
So far I haven't been able to determine the cause of the crash, I can't reproduce it. I'm wondering if it's an issue with caching the DamageSource, so I've removed the caching and will include that change in the next release. Hopefully that will fix it.

**Comment by kawazoe** [comment]
Unfortunately I didn't get a chance to take a look at this yet. We did manage to workaround the issue in our world by using rcon to kill all bats every 15 minutes + at server start. We haven't seen a crash since.

I'll try to build a version of our pack that doesn't have polymer as soon as I can; probably this weekend.

**Comment by SideswipeHoly** [comment]
I have the same issue 
[crash-2024-11-28_10.53.51-server.txt](https://github.com/user-attachments/files/17944735/crash-2024-11-28_10.53.51-server.txt)

**Comment by kawazoe** [comment]
@SideswipeHoly your crash is very different and has nothing to do with applying damages or any YUNG's mod. It looks like your server just stalled and the log doesn't really point to anything specific. You might want to open a different issue elsewhere.

**Comment by InFerNos1** [comment]
I don't have Polymer in my mod setup and am getting a similar crash.

[crash-2025-01-19_13.11.50-server.txt](https://github.com/user-attachments/files/18467343/crash-2025-01-19_13.11.50-server.txt)

**Comment by yungnickyoung** [comment]
This is probably due to my improper registration of the custom damage types. I'll be rolling out an attempted fix in the next release.

**Comment by yungnickyoung** [comment]
Sorry for the delay on this. I just released v2.0.2 which should hopefully fix the issue. Let me know if it continues to happen.
